export const FETCH_LOGO = 'FETCH_LOGO';
export const FETCH_BOWELLIST= 'FETCH_BOWELLIST';
export const FETCH_BOWELITEM= 'FETCH_BOWELITEM';
export const FETCH_CAROSEL ="FETCH_CAROSEL";
export const FETCH_PLATESSETLIST ="FETCH_PLATESSETLIST";
export const FETCH_PLATESSETITEM ="FETCH_PLATESSETITEM";
export const FETCH_MAIN ="FETCH_MAIN";
export const FETCH_PREORDER ="FETCH_PREORDER";
export const FETCH_CUPLIST ="FETCH_CUPLIST";
export const FETCH_CUPITEM ="FETCH_CUP";
export const FETCH_KNIVESLIST ="FETCH_KNIVESLIST";
export const FETCH_KNIVESITEM ="FETCH_KNIVESITEM";
export const FETCH_DISHLIST ="FETCH_DISHLIST";
export const FETCH_DISHITEM ="FETCH_DISHITEM";
export const FETCH_POTLIST ="FETCH_POTLIST";
export const FETCH_POTITEM ="FETCH_POTITEM";
export const FETCH_MIDPLATELIST ="FETCH_MIDPLATELIST";
export const FETCH_MIDPLATEITEM ="FETCH_MIDPLATEITEM";
export const FETCH_LARGEPLATELIST ="FETCH_LARGEPLATELIST";
export const FETCH_LARGEPLATEITEM ="FETCH_LARGEPLATEITEM";
export const FETCH_POLPLATELIST ="FETCH_POLPLATELIST";
export const FETCH_POLPLATEITEM ="FETCH_POLPLATEITEM";





