export const FETCH_LOGO = 'FETCH_LOGO';
export const FETCH_PRODUCTS= 'FETCH_PRODUCTS';
export const FETCH_PRODUCT= 'FETCH_PRODUCT';
export const FETCH_CAROSEL ="FETCH_CAROSEL";
export const FETCH_PLATES ="FETCH_PLATES";
export const FETCH_PLATE ="FETCH_PLATE";
